### ISSUE TITLE
nodenv install with no arguments doesn't work

### ISSUE THREAD

**Issue by olivierlacan** [ouchxp/nodenv-nvmrc#2]
When a directory contains `.node-version` file you can run `nodenv install` with [node-build](https://github.com/nodenv/node-build) installed and node-build picks up the required version then installs it.

Any chance you could allow for that? I realize that requires checking whether another plugin is installed, but I commonly default to `nodenv install` in `bin/setup`-type scripts.

PS: Thanks for this plugin, I have a ton of old projects with `.nvmrc` files all over the place and it's way easier to deal with them with this.

**Comment by ouchxp** [comment]
Thanks for the suggestion! I'll look into it shortly.

**Comment by ouchxp** [comment]
HI @olivierlacan , 
Sorry, I couldn't find a way to implement this feature, since the current `nodenv` code only allow few places to add a `hook`.

`nodenv install` is calling on `nodenv-local` then calling `nodenv-version-file`.  `nodenv install` is the only one allow adding `hooks` but only after the file has been read.

Alternatively this command `nodenv install $(cat $(nodenv version-origin))` is doing the same thing, probably you can give it a try.

**Comment by dbackeus** [comment]
Would be nice to add info regarding this to the `README` since it's a pretty major gotcha.
